name: Workflow ALNITAK
run-name: Flujo de trabajo ALNITAK

on:
  push:
    branches: [alnitak]

jobs:
  ALNITAK:
    uses: ./.github/workflows/ALNITAK-Node.yml
    with:
      node-version: "20"
      path-base: "."
